### ISSUE TITLE
Task logs show error on Moodle 3.11 booking 7.0.20.09

### ISSUE THREAD

**Issue by dasistwas** [Wunderbyte-GmbH/moodle-mod_booking#214] opened 2022-11-08 16:40 UTC
```
Execute adhoc task: mod_booking\task\send_confirmation_mails
... started 02:05:03. Current memory use 15.1MB.
send_confirmation_mails task started
... used 1 dbqueries
... used 0.0010290145874023 seconds
Adhoc task failed: mod_booking\task\send_confirmation_mails,Coding error detected, it must be fixed by a programmer: Confirmation email was not sent

```

**Comment by bernhard-wunderbyte** [comment] 2022-11-11 12:14
@dasistwas Could not reproduce this on local Moodle 3.11 with Booking v7.0.20.09:
```
Execute adhoc task: mod_booking\task\send_confirmation_mails
... started 13:07:41. Current memory use 12.3MB.
send_confirmation_mails task started
send_confirmation_mails task finished
... used 6 dbqueries
... used 0.024589061737061 seconds
Adhoc task complete: mod_booking\task\send_confirmation_mails
```
Please either **provide more information** on **how** the error happens or close this issue (with "close as not planned / won't fix").

**Closed as completed** 2022-12-30 14:21 UTC
Labels: bug, wontfix
