### ISSUE TITLE
Calendar permissions error - Moodle 3.9.14 Latest Version Booking

### ISSUE THREAD

**Issue by katcee** [Wunderbyte-GmbH/moodle-mod_booking#208] opened 2022-08-15 05:58 UTC
Hi There, 

When people with teacher/non editing teacher roles try to add people to our booking slots, they are seeing the following error: 
Sorry, but you do not have permission to update the calendar event.

[More information about this error](https://docs.moodle.org/39/en/error/moodle/nopermissiontoupdatecalendar)

×Debug info:
Error code: nopermissiontoupdatecalendar
Stack trace:
line 498 of /lib/setuplib.php: moodle_exception thrown
line 486 of /calendar/lib.php: call to print_error()
line 963 of /calendar/lib.php: call to calendar_event->update()
line 272 of /mod/booking/classes/calendar.php: call to calendar_event::create()
line 66 of /mod/booking/classes/calendar.php: call to mod_booking\calendar->booking_option_add_to_cal()
line 1101 of /mod/booking/classes/booking_option.php: call to mod_booking\calendar->__construct()
line 96 of /mod/booking/subscribeusers.php: call to mod_booking\booking_option->user_submit_response()

This has never happened before. We are wondering if there is an error in the booking code. This error occurs whether we have the option set to create a calendar entry or not.

**Comment by georgmaisser** [comment] 2022-08-17 17:48
We can't reproduce it but we wonder if it could be somehow linked to this problem?

https://moodle.org/mod/forum/discuss.php?d=363613

We don't see right now the booking connection.

**Comment by katcee** [comment] 2022-08-18 04:47
Thanks for that link. I have used one of the work arounds described and this has allowed us to side step the problem. I created a role called Calendar Editor at the system level (did not work on any other level) with the three main calendar permissions and nothing else. I then added all the teachers and non editing teachers for the relevant course to that role. This allowed them to add users without any errors. 

However it seemed to be related only to when users were added to a booking. No other calendar related activity produced the same error, so it seems that something in booking is triggering the error.

**Comment by georgmaisser** [comment] 2022-08-18 06:30
Thank you for the further explanation. I am keeping this open and we will have a further look on it.

**Comment by Sandrokkan** [comment] 2022-12-24 14:35
> Hi There,
> 
> When people with teacher/non editing teacher roles try to add people to our booking slots, they are seeing the following error: Sorry, but you do not have permission to update the calendar event.
> 
> [More information about this error](https://docs.moodle.org/39/en/error/moodle/nopermissiontoupdatecalendar)
> 
> ×Debug info: Error code: nopermissiontoupdatecalendar Stack trace: line 498 of /lib/setuplib.php: moodle_exception thrown line 486 of /calendar/lib.php: call to print_error() line 963 of /calendar/lib.php: call to calendar_event->update() line 272 of /mod/booking/classes/calendar.php: call to calendar_event::create() line 66 of /mod/booking/classes/calendar.php: call to mod_booking\calendar->booking_option_add_to_cal() line 1101 of /mod/booking/classes/booking_option.php: call to mod_booking\calendar->__construct() line 96 of /mod/booking/subscribeusers.php: call to mod_booking\booking_option->user_submit_response()
> 
> This has never happened before. We are wondering if there is an error in the booking code. This error occurs whether we have the option set to create a calendar entry or not.

I encountered the same error. Moodle 3.11, Fordson theme

**Comment by Sandrokkan** [comment] 2022-12-26 10:04
> Non possiamo riprodurlo ma ci chiediamo se possa essere in qualche modo collegato a questo problema?
> 
> https://moodle.org/mod/forum/discuss.php?d=363613
> 
> Al momento non vediamo la connessione di prenotazione.
The problem also occurs when assigning an option to a user who can book for other users. When this user will book for other users the same error will appear

**Comment by gemguardian** [comment] 2022-12-27 10:41
> Thanks for that link. I have used one of the work arounds described and this has allowed us to side step the problem. I created a role called Calendar Editor at the system level (did not work on any other level) with the three main calendar permissions and nothing else. I then added all the teachers and non editing teachers for the relevant course to that role. This allowed them to add users without any errors.
> 
> However it seemed to be related only to when users were added to a booking. No other calendar related activity produced the same error, so it seems that something in booking is triggering the error.

Thank you - this work around solved our issue for now.

**Comment by Sandrokkan** [comment] 2022-12-27 10:49
> > Grazie per quel collegamento. Ho usato uno dei work around descritti e questo ci ha permesso di aggirare il problema. Ho creato un ruolo chiamato Calendar Editor a livello di sistema (non funzionava su nessun altro livello) con le tre autorizzazioni principali del calendario e nient'altro. Ho quindi aggiunto a quel ruolo tutti gli insegnanti e gli insegnanti non editori per il corso pertinente. Ciò ha consentito loro di aggiungere utenti senza errori.
> > Tuttavia sembrava essere correlato solo a quando gli utenti venivano aggiunti a una prenotazione. Nessun'altra attività correlata al calendario ha prodotto lo stesso errore, quindi sembra che qualcosa nella prenotazione stia attivando l'errore.
> 
> Grazie - questa soluzione ha risolto il nostro problema per ora.

This solution works it doesn't work if you use the "modify teachers" command and assign the possibility to book for other users to a participant

**Comment by gemguardian** [comment] 2022-12-27 10:59
We actually have this issue with:

- Enrolled participants with Teacher/editing teacher rol
- Teacher using the 'book other users" 

The role has: the 3 major calender  + the make booking for other users premissions

As well _ it does not happen to everyone!

**Comment by Sandrokkan** [comment] 2022-12-27 11:01
Exactly the same thing happens to us too

**Comment by bernhard-wunderbyte** [comment] 2022-12-27 12:38
Fixed in Booking v7.0.22.13 (Branch: MOODLE_39_STABLE)

**Closed as completed by bernhard-wunderbyte** 2022-12-27 12:38 UTC
Labels: bug

**Comment by bernhard-wunderbyte** [comment] 2022-12-27 13:11
@dasistwas will publish this on Moodle.org in January, I guess.

If you cannot wait, you can just get the newest version (for the Moodle 3.9 branch) from Github: https://github.com/Wunderbyte-GmbH/moodle-mod_booking/archive/refs/heads/MOODLE_39_STABLE.zip

**Comment by dasistwas** [comment] 2023-01-03 10:56
the bugfix is now published on moodle.org
