### ISSUE TITLE
Group enrollment via booking

### ISSUE THREAD

**Issue by venturamartha** [Wunderbyte-GmbH/moodle-mod_booking#468] opened 2024-04-15 03:14 UTC
**Describe the bug**
Bug - Group enrollment via booking

**Versions uses**
Moodle version: Moodle 4.1.8 (Build: 20231222)
Boooking version: 8.2.2 2024040200

**To Reproduce**
1. Go to the edit booking option
2. Click on Connected Moodle course (choose the course to be connected with)
3. Clicked on Save
4. See error:
Can't find data record in database table course.
File: /lib/dml/moodle_database.php
Line: 1654

SELECT * FROM {course} WHERE id = ?
[array (
  0 => '0',
)]
Error code: invalidrecord
* line 1654 of /lib/dml/moodle_database.php: dml_missing_record_exception thrown
* line 1630 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
* line 250 of /group/lib.php: call to moodle_database->get_record()
* line 1455 of /mod/booking/classes/booking_option.php: call to groups_create_group()
* line 130 of /mod/booking/classes/option/fields/addtogroup.php: call to mod_booking\booking_option->create_group()
* line 227 of /mod/booking/classes/option/fields_info.php: call to mod_booking\option\fields\addtogroup::save_data()
* line 3393 of /mod/booking/classes/booking_option.php: call to mod_booking\option\fields_info::save_fields_post()
* line 214 of /mod/booking/classes/form/option_form.php: call to mod_booking\booking_option::update()
* line 77 of /lib/form/classes/external/dynamic_form.php: call to mod_booking\form\option_form->process_dynamic_submission()
* line 262 of /lib/externallib.php: call to core_form\external\dynamic_form::execute()
* line 81 of /lib/ajax/service.php: call to external_api::call_external_function()

**Expected behavior**
The expected behaviour was to have the settings save and the groups work with the Booking.

**Screenshots**
Groups is working in Booking for one of the sessions only. The highlighted group was created by Moodle.
 
![image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/165815240/006096fd-1159-4b6e-9b07-6c55c238b5e8)

It’s only working for one session (West)
 
I compared the settings for the 4 sessions and the difference is the Connected Moodle course.
![image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/165815240/fe693d41-3ba8-4baf-bb68-c794d9f35efe)

 
 
However, when I try to connect the other three sessions, I get an error message.
 
![image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/165815240/8e2752ad-8202-4639-bc93-fd3658768ecd)

**Additional context**

**Comment by georgmaisser** [comment] 2024-04-15 11:43
Thank you Martha for reporting this. We'll fix this asap!

**Comment by georgmaisser** [comment] 2024-04-15 12:19
Hi Martha, the issue is fixed in b0285d1157cfb6c6525b4632a6a15817a776d308

Currently, it's in the branch MOODLE_401_DEV, but it will be in main & stable very soon. We'll create an automated test for it so it won't escape our attention in the future.

**Closed as completed by georgmaisser** 2024-04-15 12:19 UTC
Labels: bug

**Comment by venturamartha** [comment] 2024-04-19 22:21
Before we push it to production we have to wait to see when the code changes have been tested and confirmed to work and any other code patches are added to the plugin so that we are assured that it at least meets the minimum requirements for stability.  do you have any idea when this will happen? so far we have not seen anything updated on the stable branch of this plugin as of yet.  Thank you!
