### ISSUE TITLE
Test filter for teachers

### ISSUE THREAD

**Issue by eynimeni** [Wunderbyte-GmbH/moodle-mod_booking#647] opened 2024-10-10 14:28 UTC
There is a new type of filter that we need to extend the tests for.
In the instance of booking one can filter the list for teachers

<img width="393" alt="Screenshot 2024-10-10 at 16 07 50" src="https://github.com/user-attachments/assets/2626a6ac-a353-4b45-befe-c93159a9b0be">

all teachers in the corresponding bookingoptions (of this booking instance) should be listed here
for example if we have 3 bookingoptions
a) without teachers
b) with 1 teacher "anna"
c) with 3 teachers "anna", "berta", "caesar"

the filter should display  "anna", "berta", "caesar"
no filter active -> see a), b), c)
filter for anna -> see option b) & c)
filter for berta -> see option c)
filter for anna & berta -> see b) & c)

**Comment by semteacher** [comment] 2024-10-11 07:19
1. Behat test for the "Filter by Teacher" feature already avaialble except not cove case of 2 teachers for option. Will be adjusted
2. It works peoperly with latest booking and "main" brahch of wb_table (ends up with https://github.com/Wunderbyte-GmbH/moodle-local_wunderbyte_table/commit/dd84897c8cbc1d7b1ad5f4abdef342e595b190f1 commit now)
3. UPD: teacher filter start working again.
Date filter not, external function returns  Warning: Undefined array key \"courseendtime\" in [dirroot]\/local\/wunderbyte_table\/classes\/wunderbyte_table.php on line 1393",
UPD: directly caused by missing "courseendtime" in "filtersettings" but presence of it in the "filterobject"
![Image](https://github.com/user-attachments/assets/dd7877fe-3d96-4755-a6e8-20b737a1a2c4)
![Image](https://github.com/user-attachments/assets/466d9e80-b78e-455c-8ac0-a3ea0e9cfdf7)

**Comment by semteacher** [comment] 2024-10-11 12:09
Fixed with https://github.com/Wunderbyte-GmbH/moodle-local_wunderbyte_table/commit/bfa114d94ea96e1cbdd044025fac7104041e437e
Behat test adjusted to support few teachers https://github.com/Wunderbyte-GmbH/moodle-mod_booking/commit/227538faa37f48e142e9a9d0cc323dee081073e9

**Comment by semteacher** [comment] 2024-10-11 12:18
Better to rename "course time" filter to specificaly points that it menas booking optios' "course tine". Because, as a teacher who works with Moodle every day - when i see "course" - I am thinking exactly about entire course

**Closed as completed** 2024-10-11 17:34 UTC
Labels: bug, enhancement
