### ISSUE TITLE
Error when deleting a booking option

### ISSUE THREAD

**Issue by demontech** [Wunderbyte-GmbH/moodle-mod_booking#68] opened 2016-10-20 03:04 UTC
Hi David,

I'm getting this error when I tried to delete a booking option in M3.0 with your latest version:

image
![image](https://cloud.githubusercontent.com/assets/8148238/19544926/3d704642-9637-11e6-8ce3-264a6336e586.png)

Thanks!

**Comment by dasistwas** [comment] 2016-12-09 12:25
Hi,

I can't reproduce this error. Does it still exist? Could you provide a course backup or backup of the booking instance in order to reproduce it.

Thanks,
David

**Comment by demontech** [comment] 2016-12-21 02:47
It was happening for some booking not for all of them. I ended up deleted them from the database.

very strange

**Comment by dasistwas** [comment] 2017-05-06 15:51
I close this. Does not seem to happen anymore.

**Closed as completed by dasistwas** 2017-05-06 15:51 UTC
